# Classification - Mini-Project 2

***Edit this cell with your name(s), tutorial number(s) and ID(s)***

---

Name: Mohamed Fathy Mahmoud Mohamed

ID: 43-17605

Tutorial: T-01

---

Name: Sherif Wael

ID: 43-2241

Tutorial: T-01

---

## Dataset Description

The data set includes information about:

- Customers who left within the last month – the column is called Churn
- Services that each customer has signed up for – phone, multiple lines, internet, online security, online backup, device protection, tech support, and streaming TV and movies
- Customer account information – how long they’ve been a customer, contract, payment method, paperless billing, monthly charges, and total charges
- Demographic info about customers – gender, age range, and if they have partners and dependents

Each row represents a customer, and each column represents customer attributes as described below.

| Column | Description|
|-|-|
|gender|Whether the customer is a male or a female|
|SeniorCitizen| Whether the customer is a senior citizen or not (1, 0)|
|Partner|Whether the customer has a partner or not (Yes, No)|
|Dependents|Whether the customer has dependents or not (Yes, No)|
|tenure| Number of months the customer has stayed with the company|
|PhoneService|Whether the customer has a phone service or not (Yes, No)|
|MultipleLines|Whether the customer has multiple lines or not (Yes, No, No phone service*)|
|InternetService|Customer’s internet service provider (DSL, Fiber optic, No)|
|OnlineSecurity|Whether the customer has online security or not (Yes, No, No internet service**)|
|OnlineBackup|Whether the customer has online backup or not (Yes, No, No internet service)|
|DeviceProtection|Whether the customer has device protection or not (Yes, No, No internet service)|
|TechSupport|Whether the customer has tech support or not (Yes, No, No internet service)|
|StreamingTV|Whether the customer has streaming TV or not (Yes, No, No internet service) |
|StreamingMovies|Whether the customer has streaming movies or not (Yes, No, No internet service)|
|Contract|The contract term of the customer (Month-to-month, One year, Two year)|
|PaperlessBilling|Whether the customer has paperless billing or not (Yes, No)|
|PaymentMethod|The customer’s payment method (Electronic check, Mailed check, Bank transfer (automatic), Credit card (automatic))|
|MonthlyCharges|The amount charged to the customer monthly|
|TotalCharges|The total amount charged to the customer|
|Churn|Whether the customer churned or not (Yes or No)|

\* No phone service means the customer's plan does not include calling (could be a data-only plan)

\*\* No internet service means the customer's plan does not include internet/data and so the addon package does not apply

## Importing Libraries & Dataset

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
plt.style.use("seaborn")

df = pd.read_csv('https://raw.githubusercontent.com/GUC-DM/W2021/main/data/telecom_churn.csv')
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...       $29.85/m       $29.85     No
1  5575-GNVDE    Male              0  ...       $56.95/m      $1889.5     No
2  3668-QPYBK    Male              0  ...       $53.85/m      $108.15    Yes
3  7795-CFOCW    Male              0  ...        $42.3/m     $1840.75     No
4  9237-HQITU  Female              0  ...        $70.7/m      $151.65    Yes

[5 rows x 21 columns]

## Data Inspection

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        6976 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   object
 19  TotalCharges      6180 non-null   object
 20  Churn             7032 non-null   object
dtypes: int64(2), object(19)
memory usage: 1.1+ MB

In [24]:
df.describe(include='O')

        customerID gender Partner  ... MonthlyCharges TotalCharges Churn
count         6976   7032    7032  ...           7032         6180  7032
unique        6976      2       2  ...           1584         5783     2
top     8401-EMUWF   Male      No  ...       $20.05/m        $20.2    No
freq             1   3549    3639  ...             61            8  5163

[4 rows x 19 columns]

In [25]:
df.describe()

       SeniorCitizen       tenure
count    7032.000000  7032.000000
mean        0.162400    32.421786
std         0.368844    24.545260
min         0.000000     1.000000
25%         0.000000     9.000000
50%         0.000000    29.000000
75%         0.000000    55.000000
max         1.000000    72.000000

In [26]:
df.isna().sum()

customerID           56
gender                0
SeniorCitizen         0
Partner               0
Dependents            0
tenure                0
PhoneService          0
MultipleLines         0
InternetService       0
OnlineSecurity        0
OnlineBackup          0
DeviceProtection      0
TechSupport           0
StreamingTV           0
StreamingMovies       0
Contract              0
PaperlessBilling      0
PaymentMethod         0
MonthlyCharges        0
TotalCharges        852
Churn                 0
dtype: int64

In [45]:
categorical_col = []
for column in df.columns:
    if df[column].dtype == object and len(df[column].unique()) <= 50:
        categorical_col.append(column)
        print(f"{column} : {df[column].unique()}")
        print("====================================")

gender : ['Female' 'Male']
====================================
Partner : ['Yes' 'No']
====================================
Dependents : ['No' 'Yes']
====================================
PhoneService : ['No' 'Yes']
====================================
MultipleLines : ['No phone service' 'No' 'Yes']
====================================
InternetService : ['DSL' 'Fiber optic' 'No']
====================================
OnlineSecurity : ['No' 'Yes' 'No internet service']
====================================
OnlineBackup : ['Yes' 'No' 'No internet service']
====================================
DeviceProtection : ['No' 'Yes' 'No internet service']
====================================
TechSupport : ['No' 'Yes' 'No internet service']
====================================
StreamingTV : ['No' 'Yes' 'No internet service']
====================================
StreamingMovies : ['No' 'Yes' 'No internet service']
====================================
Contract : ['Month-to-month' 'One year' 'Two year']
====================================
PaperlessBilling : ['Yes' 'No']
====================================
PaymentMethod : ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
====================================
Churn : ['No' 'Yes']
====================================

## Data Pre-processing

Drop the customer ID column

In [27]:
df = df.drop('customerID', axis = 1)

change type of senior citizen to categoical

In [43]:
df['SeniorCitizen'] = pd.Categorical(df.SeniorCitizen)

clean the values of Monthly charges and total charges

In [28]:
print(df['MonthlyCharges'].map(lambda x: x[0]).value_counts())
print(df['MonthlyCharges'].map(lambda x: x[-2:]).value_counts())

$    7032
Name: MonthlyCharges, dtype: int64
/m    7032
Name: MonthlyCharges, dtype: int64

In [29]:
df['MonthlyCharges'] = df['MonthlyCharges'].map(lambda x: x.replace('$', ''))
df['MonthlyCharges'] = df['MonthlyCharges'].map(lambda x: float(x.replace('/m', '')))

In [30]:
print(df['TotalCharges'].dropna().map(lambda x: x[0]).value_counts())

$    6180
Name: TotalCharges, dtype: int64

In [31]:
df['TotalCharges'] = df['TotalCharges'].map(lambda x: float(x.replace('$', ''))  if not pd.isnull(x) else np.nan)

In [32]:
print(df['TotalCharges'])

0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
         ...
7027    1990.50
7028    7362.90
7029     346.45
7030     306.60
7031    6844.50
Name: TotalCharges, Length: 7032, dtype: float64

In [33]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges
count    7032.000000  7032.000000     7032.000000   6180.000000
mean        0.162400    32.421786       64.798208   2281.933932
std         0.368844    24.545260       30.085974   2271.511755
min         0.000000     1.000000       18.250000     18.850000
25%         0.000000     9.000000       35.587500    392.612500
50%         0.000000    29.000000       70.350000   1390.225000
75%         0.000000    55.000000       89.862500   3785.900000
max         1.000000    72.000000      118.750000   8684.800000

### Fill the missing values in the total charges using regression

The values of the total charges can be imputed using regression with the attributes monthly charges and tenture

In [34]:
train_set = df[df['TotalCharges'].isnull()==False]
test_set = df[df['TotalCharges'].isnull()==True]
x_train = train_set[['tenure','MonthlyCharges']]
y_train = train_set['TotalCharges']

x_test = test_set[['tenure','MonthlyCharges']]
y_test = test_set['TotalCharges']

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import PoissonRegressor
possion_model = PoissonRegressor()
linear_model = LinearRegression()
linear_model.fit(x_train,y_train)
possion_model.fit(x_train,y_train)
y_pred = linear_model.predict(x_test)
y_pred_Poisson = possion_model.predict(x_test)

In [36]:
y_pred_Poisson[y_pred_Poisson<= 0]

array([], dtype=float64)

In [37]:
y_pred[y_pred<= 0]

array([-1360.29476234, -1387.01776318,  -370.35255284, -1196.39369058,
       -1340.69789507,  -393.5124869 ,  -275.34092859,  -191.60467154,
        -710.42864521, -1370.98396268,  -644.90757348, -1101.7735422 ,
        -778.12900787,  -162.11411902,  -149.24562775, -1087.52127509,
        -162.11202513,  -625.11392132,  -409.5462874 ,  -469.72275896,
       -1387.01776318, -1158.38694699, -1182.14142347,  -937.27792801,
        -446.36813391,  -462.59662541,    -8.30770516, -1410.17769723,
        -370.5535255 ,  -344.61975809,  -293.15626248, -1036.25247047,
        -248.21807633, -1365.63936251,  -473.09113474,  -731.21459734,
        -145.68046709,  -270.19101942,  -469.52806796,  -311.36726002,
        -216.54823287,  -509.90879348,  -249.99960972,  -296.12478683,
        -777.73125033,  -457.64978278,  -100.75065649, -1376.32856284,
         -39.18412742,  -109.65832343,  -995.67286619,   -15.23286606,
       -1333.57176151, -1096.42894204,  -490.90646863,  -712.2101786 ,
       -1303.68135756,  -276.92358321,  -462.40193441,  -342.24368228,
        -111.43985682,  -887.19820824,  -636.39766408,  -264.84641925,
       -1395.92543012,  -439.23990647,  -430.33433341, -1388.79929656,
        -269.401786  , -1059.41240453, -1145.12488596,  -314.53466314,
        -877.10145645, -1180.35989008,  -271.77786181, -1278.73989012,
        -237.528876  ,  -261.48432513,  -606.10950259,  -818.70651827,
       -1360.29476234,  -703.10572678, -1376.32856284,  -791.98351744,
       -1376.32856284, -1005.96640286,  -434.09209119, -1358.51322895,
        -506.94026913, -1367.4208959 ,  -784.85738389, -1356.73169557,
        -269.59647699,   -64.12559486,  -249.99960972,  -928.37026107,
        -781.296411  ,  -253.96252792,  -269.99632842, -1310.80749111,
        -526.93070617,  -353.72839769,  -372.73072255,   -95.40605632,
        -310.97159636, -1323.27822483, -1360.29476234,  -348.38379753,
        -307.40852959,  -391.53626251,   -87.88007134, -1192.8306238 ,
        -305.6269962 ,  -251.78114311,  -197.74478679, -1018.43713659,
       -1358.51322895,  -241.09194277,  -635.20857923,   -20.57746622,
        -923.0256609 , -1392.36236334,  -582.94956853,  -514.06640268,
        -993.29888426,  -685.88493531])

In [38]:
df.TotalCharges.isna().sum()

852

In [39]:
df.TotalCharges = df.TotalCharges.fillna(pd.Series(y_pred_Poisson,index=y_test.index))

In [44]:
df.describe()

            tenure  MonthlyCharges  TotalCharges
count  7032.000000     7032.000000   7032.000000
mean     32.421786       64.798208   2281.188725
std      24.545260       30.085974   2279.825664
min       1.000000       18.250000     18.850000
25%       9.000000       35.587500    441.507139
50%      29.000000       70.350000   1379.950000
75%      55.000000       89.862500   3715.550000
max      72.000000      118.750000  11299.322048

## Exploratory Data Analysis

**Q1: What are the most correlated attributes with customer churn?**

**Visualization**

**Answer for Q1**: Your answer here

**Q2: Which payment method has the highest churn rate?**

**Visualization**

In [ ]:
categorical_features = categorical_col.copy()
categorical_features.remove('Churn')

**Answer for Q2**: Your answer here

**Q3: After how many months do customers commonly churn?** (Hint: show and interpret the distribution)

**Visualization**

**Answer for Q3**: Your answer here

## Modelling

## Evaluation

## Decision Tree Visualization

## Bonus (Optional)